trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: DatabricksSecrets

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install databricks-cli
    databricks auth login 
    databricks bundle validate
    databricks bundle deploy 
  displayName: 'Deploy Databricks Asset Bundle to Dev'
