# trigger:
#   branches:
#     include:
#       - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DATABRICKS_HOST: 'https://adb-550289489940613.13.azuredatabricks.net/'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python'
  
- task: AzureCLI@2
  inputs:
    azureSubscription: 'dab_poc'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Install Databricks CLI v2
      Invoke-WebRequest -Uri https://raw.githubusercontent.com/databricks/setup-cli/main/install.ps1 -OutFile install.ps1
      .\install.ps1

      # Install uv (Rust-based tool)
      Invoke-WebRequest -Uri https://install.uv.dev -OutFile install-uv.ps1
      .\install-uv.ps1

      # Add uv to PATH
      $env:Path += ";$env:USERPROFILE\.cargo\bin"

      # Authenticate with Databricks using Azure CLI context
      databricks auth azure-login --host $env:DATABRICKS_HOST

      # Validate and deploy
      databricks bundle validate
      databricks bundle deploy --target dev
  displayName: 'Deploy Databricks Asset Bundle to Dev'

