# trigger:
#   branches:
#     include:
#       - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DATABRICKS_HOST: 'https://adb-550289489940613.13.azuredatabricks.net/'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'dab_poc'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Install Databricks CLI v2
      curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      # Install uv and add it to PATH
      curl -Ls https://install.uv.dev | sh
      export PATH="$HOME/.cargo/bin:$PATH"

      # Authenticate using Azure CLI context
      databricks auth azure-login --host $DATABRICKS_HOST

      # Validate and deploy the asset bundle
      databricks bundle validate
      databricks bundle deploy --target dev
  displayName: 'Deploy Databricks Asset Bundle to Dev'

